// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm2TE6xvVTyLnGpFilWsJAqJbbsGtOekw',
    appId: '1:825393055383:web:ba768d046b7c408cb80bd2',
    messagingSenderId: '825393055383',
    projectId: 'tengashopping-39827',
    authDomain: 'tengashopping-39827.firebaseapp.com',
    storageBucket: 'tengashopping-39827.appspot.com',
    measurementId: 'G-JCK6JJL1R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfNBCAANHF_K_sNoT6fsOZS4jyhAIwvG4',
    appId: '1:825393055383:android:6dfac89a30804ffeb80bd2',
    messagingSenderId: '825393055383',
    projectId: 'tengashopping-39827',
    storageBucket: 'tengashopping-39827.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnv00ysJOGz1raP3HAUO91_ESskUTHBF8',
    appId: '1:825393055383:ios:fb244f8587be0bf7b80bd2',
    messagingSenderId: '825393055383',
    projectId: 'tengashopping-39827',
    storageBucket: 'tengashopping-39827.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnv00ysJOGz1raP3HAUO91_ESskUTHBF8',
    appId: '1:825393055383:ios:fb244f8587be0bf7b80bd2',
    messagingSenderId: '825393055383',
    projectId: 'tengashopping-39827',
    storageBucket: 'tengashopping-39827.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
